### ISSUE TITLE
Swoole Factory

### ISSUE THREAD

**Issue by nhlm** [php-earth/swoole-engine#1]
I recommend to implement a swoole factory instead of a raw instance invocation naturally based on a protocol-level syntax which is comparable to DSNs:

```yaml
swoole:
  webserver:
    dsn: 'http://0.0.0.0'
  session:
    dsn: 'tcp://127.0.0.1'
    encryption: libsodium
    private: some128bitprivatekeyhexrepresentation
    public: [
      - host: "somewhere.php.earth"
         key: some128bitpublickeyhexrepresentation
      - host: "elsewhere.php.earth"
         key: another128bitpublickeyhexrepresentation
    ]
  websocket:
    dsn: 'websocket://path/to/socketfile.socket'
```

This config syntax will create:
* an instance of a swoole HTTP server listening on any network level named `webserver`
* an instance of a swoole TCP server listening on localhost, used to manage sessions cross domain
* an instance of a swoole web socket server listening on a web socket.

Maybe this would provide a more generic swoole engine implementation that could be widely used.

What do you think about this recommendation?
